### ISSUE TITLE
editing rendering error with this applied

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/roswiki#115]
I can not edit the tf Introduction to tf page now. I think it's a result of https://github.com/ros-infrastructure/roswiki/pull/114

It looks like @mikepurvis just updated it to use the new rendering: http://wiki.ros.org/tf/Tutorials/Introduction%20to%20tf?action=diff&rev1=97&rev2=98

The output of the text editor is only: http://wiki.ros.org/action/edit/tf/Tutorials/Introduction%20to%20tf?action=edit&editor=text

```
<input type="checkbox" name="trivial" id="chktrivialtop" value="1"  onclick="toggle_trivial(this)"><label for="chktrivialtop">Trivial change</label>
```

I think we're crashing the rendering engine.

**Comment by tfoote** [comment]
I can confirm that adding $ROS_DISTRO to a page breaks the preview too. I tried using it here: http://wiki.ros.org/teleop_twist_keyboard

**Comment by mikepurvis** [comment]
Looking now.

It doesn't happen with JS off, but there isn't actually an explicit JS error showing up in the console. More details to come.

**Comment by mikepurvis** [comment]
Still not entirely clear to me _why_ it's happening, but it's definitely a result of the `$("#page").html(replaced);` line. The sledgehammer fix would be to just avoid the replacement when a textarea is present, but there may be a more elegant solution. Will have a PR shortly.
