### ISSUE TITLE
Macro to help organize the wiki.ros.org/Robots page

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/roswiki#122]
Currently it is just a MoinMoin wiki table and it has no apparent order.

I think it would be simpler if there was a macro to declare a robot and another macro to render it.

I think we should just render it alphabetically for fairness and maybe later we could have promoted sections or a sortable rendering (based on name or date updated/added).

The main point is that if there is a macro to declare and a macro to render then individuals cannot affect the order arbitrarily.

**Comment by wjwwood** [comment]
http://wiki.ros.org/Robots

**Comment by tfoote** [comment]
resolved in #123
