### ISSUE TITLE
Robots page seems broke

### ISSUE THREAD

**Issue by jihoonl** [ros-infrastructure/roswiki#125]
http://wiki.ros.org/Robots/ 

Also the page links are pointing to Robots/Robots/\<robot name\> 

![robots_page](https://cloud.githubusercontent.com/assets/1556736/6793160/2f41d462-d204-11e4-962e-5343822257fe.png)

**Comment by tfoote** [comment]
The images missing happens if you load the page too often. There's a throttle on how many times in a minute you can load attachments. (60 in 60 seconds I believe) 

That was dialed down due to spam, we can probably increase that now. 

The links seem to always be being interpreted as relative instead of only being relative with a leading `/`

**Comment by jihoonl** [comment]
So should the link be like /Robots/\<robot name\>?

**Comment by tfoote** [comment]
No `Robots/<robot_name>` is correct. If you start with the `/` it should be relative then. (moin moin is backwards from standard pathing.)

The macro probably needs an update on what syntax it gives the macros.  

Possibly here: https://github.com/ros-infrastructure/roswiki/blob/master/macro/RobotTable.py#L33

**Comment by wjwwood** [comment]
Yeah, the image loading is a throttling artifact, I don't get it, but on a few which are actually broken links:

![screen shot 2015-03-23 at 9 37 12 pm](https://cloud.githubusercontent.com/assets/100427/6795890/86a93592-d1a5-11e4-8435-fab397e50324.png)

**Comment by jihoonl** [comment]
When I refresh three times in a row, the throttling started to happen. 

BTW, I wonder if it is possible to put distribution info on robots page. Current format is hard to know whether robot is supporting which distributions. For example, [NXT](http://wiki.ros.org/Robots/NXT) has been unmaintained since hydro. It would be nice if which robots are supporting indigo..

**Comment by wjwwood** [comment]
@jihoonl We could add that with badges or something. I spent a lot of time on it already, if you're interested in modifying it further I'll help get it merged with a review.

As for the linking I think that's a bug, I guess I can try to look into it tomorrow, but I'm really busy. I'd appreciate any help with that.

**Comment by wjwwood** [comment]
I'm going to close this for now, please open a new issue/pull request to track other features.
