### ISSUE TITLE
"Code API" link goes to Apache's index page

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/roswiki#145]
e.g. for robot_state_publisher [jade](http://docs.ros.org/jade/api/robot_state_publisher) or [indigo](http://docs.ros.org/indigo/api/robot_state_publisher/), I now see a bland index page. 

![roswiki_codeapi_apacheindex](https://cloud.githubusercontent.com/assets/1840401/12500615/a5721c74-c069-11e5-9238-b96e35b09cec.png)

Under `html` I believe I see what we expect.

Is this part of recent work and do we just have to wait for a few moments for it to get fixed?

**Comment by dirk-thomas** [comment]
The "Code API" link should point to the `html` subfolder directly (it did before). That is certainly due to the new build farm and it needs fixing. I will look into it.

**Comment by dirk-thomas** [comment]
The `robot_state_publisher` page for Jade has been fixed. All other pages will be fixed when the doc jobs have been run another round.
