### ISSUE TITLE
Packages show 'released' badge on wiki even when not released

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/roswiki#154]
See fi [wiki/fanuc](http://wiki.ros.org/fanuc): that has definitely not been released into Jade, but shows the `Released` badge anyway.

IIUC `macro/headers.py::get_badges(..)` adds the `Released` badge whenever the `release_jobs` key is non-empty ([here](https://github.com/ros-infrastructure/roswiki/blob/e03c652de39a19aa62d7cfe5005e07e2b2b3e502/macro/headers.py#L179-L180)). Somehow `release_jobs` is fully populated for the [Jade version](http://docs.ros.org/jade/api/fanuc_m10ia_support/manifest.yaml) of `fanuc_m10ia_support/manifest.yaml` and thus it gets the badge.

This is probably more an issue on the 'generator side', but I wasn't too sure where to report this.

**Comment by dirk-thomas** [comment]
Thank you for reporting this. It is a problem in the new build farm code.

The same kind of problem exists for the generated documentation of only released package which don't have devel jobs. Their manifest.yaml lists devel jobs even without the repo having a `source` entry (e.g. http://docs.ros.org/jade/api/cv_backports/manifest.yaml).

ros-infrastructure/ros_buildfarm#208 will address both issues.

**Comment by gavanderhoorn** [comment]
Great. Thanks for fixing.
