### ISSUE TITLE
pls add our robots in ROS wiki robots page

### ISSUE THREAD

**Issue by ykknkgw** [ros-infrastructure/roswiki#157]
Hi all,
I'm Yuki Nakagawa, RT Corporation,Japan.
We'd like to add our robots force control robot arm "NEKONOTE" and Raspberry Pi Mouse (small wheel robot) to ROS wiki.
Pls add whitelist.

all the best,
Yuki Nakagawa
RT Corp.

**Comment by tfoote** [comment]
Please comment in #139 with your ROS wiki username to be added to the whitelist. Then you will be able to add your robot information yourself.
