### ISSUE TITLE
Mirrors should also mirror javascript and wiki level images

### ISSUE THREAD

**Issue by eitanme** [ros-infrastructure/roswiki#16]
The mirrors don't actually mirror javascript or images for the wiki right now which results in pages looking pretty bad. For example, the distro buttons do not work. We should probably fix this.

**Comment by tfoote** [comment]
Injecting the rest of the javascript needed for most pages: https://github.com/ros-infrastructure/roswiki/commit/aa288fabd2ebd43fb1d5ac5869523bf4f7a40143 so that the console doesn't complain about missing resources.
