### ISSUE TITLE
ROS:No devices connected.... waiting for devices to be connected

### ISSUE THREAD

**Issue by QinZiwen** [ros-infrastructure/roswiki#167]
A question hits me that [ INFO] [1463576402.886843254]: No devices connected.... waiting for devices to be connected when roslaunch freenect_launch freenect-debug.launch . help me, please!

**Comment by wjwwood** [comment]
This isn't the right place to ask questions like this. Please see: http://wiki.ros.org/Support

> [ROS Answers](http://answers.ros.org/) should be used as the first step in requesting help, as described below (and in [this related question](http://answers.ros.org/question/10/when-should-one-use-answersrosorg-vs-the-ros-users)).

**Comment by QinZiwen** [comment]
Thank you!
