### ISSUE TITLE
CodeRef.py not reflect the user's selection on the button (that's realized by Version)

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/roswiki#17]
Line-by-line code snippet at http://www.ros.org/wiki/pluginlib/Tutorials/Writing%20and%20Using%20a%20Simple%20Plugin#Registering_the_Plugins always refer to the one that's shown by selecting Groovy button, which comes 1st in the source of the wiki page (checked on Jan 8, 2013).

**Comment by esteve** [comment]
Fixed.
