### ISSUE TITLE
Robots page is now a large fraction of the server load

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/roswiki#171]
Since this is a very popular page. The current macro is nice, but we should find a more efficient solution. Possibly move this off the wiki to a statically generated github page where we can take PRs and embed it into the wiki page. 

![robots_load](https://cloud.githubusercontent.com/assets/447804/16167607/1b7ec2a8-34ac-11e6-9fdd-d7b3bcc12cbb.png)

**Comment by dhood** [comment]
the page now redirects to http://robots.ros.org/ (see https://github.com/ros-infrastructure/robots.ros.org) thanks to work by @tfoote. I understand this to have resolved the issue so will close this
