### ISSUE TITLE
comment requested re: white list

### ISSUE THREAD

**Issue by dabeegmon** [ros-infrastructure/roswiki#180]
Greetings
Directions were to leave a comment to be 'white listed'.

Have left comment.

Da beegmon

**Comment by tfoote** [comment]
Please comment on #139 with your ROS wiki username.

**Comment by dabeegmon** [comment]
On Fri, Aug 26, 2016 at 3:14 PM, Tully Foote <notifications@github.com>
wrote:

> Please comment on #139
> <https://github.com/ros-infrastructure/roswiki/issues/139> with your ROS
> wiki username.
>
>
> Would love to - - - if I could actually figure out what the blazes you are
asking me to do!

There is no comment button so what hoop is it that I am to jump through now?

Dee

**Comment by wjwwood** [comment]
If you go to issue https://github.com/ros-infrastructure/roswiki/issues/139 (click on the link) there is a comment box at the bottom of the page...
