### ISSUE TITLE
Surge protection triggers due to coorporate firewall

### ISSUE THREAD

**Issue by NikolausDemmel** [ros-infrastructure/roswiki#182]
It seems the ROS wiki surge protection triggers because of Bosch employees being behind the same proxy and thus causing too many requests from the same IP.

It might have happened before, but I am personally witnessing it for the first time now. We have been locked out for > 30 Minutes now, maybe longer.

I just read http://wiki.ros.org/HelpOnConfiguration/SurgeProtection. As a workaround it is suggested to log in with a ROS wiki user, but it is not possible to do so while you are already locked out.

It is a big company (~300000 employees) and it is not viable to even find out who is using ROS, let alone coordinate access to the ROS wiki.

The Bosch internet proxies have fixed IP addresses. Might it be possible to add exceptions or at least raise limits for the relevant list of IPs?

**Comment by NikolausDemmel** [comment]
PS, the response from the wiki reads:

```
Surge protection
Warning:

You triggered the wiki's surge protection by doing too many requests in a short time.

Please make a short break reading the stuff you already got.

When you restart doing requests AFTER that, slow down or you might get locked out for a longer time!
```

We are still not able to connect to the wiki as of now.

**Comment by NikolausDemmel** [comment]
Looks like we can access the wiki again. Outage for us was > 4h.

Maybe someone could still comment on the possibility of whitelisting certain IPs to avoid this in the future.

**Comment by wjwwood** [comment]
@NikolausDemmel sorry to hear that. I'm not familiar with MoinMoin's surge protection, so I'll wait for @tfoote to comment, but he's on vacation, so expect to wait a few days for that at least.

**Comment by NikolausDemmel** [comment]
It is not super urgent, since it seems it happens infrequently for now. We can wait for @tfoote no problem. I will also post again should I notice additional occurances.

**Comment by dirk-thomas** [comment]
After a short grep through the wiki code it doesn't have a config option to white list addresses for the surge protection. But the code compares the remote IP against a static white list (basically everything local) which could easily be extended. So adding a few IP addresses should be easily possible.

Should we do that or will that negatively affect the wiki performance? Instead we could increase the limits for a known list of hosts?

**Comment by tfoote** [comment]
We could look at adding some specific IPs, though from the site you linked it sounds like MoinMoin's recommended approach is to suggest users login. You should be able to login, the surge limits are per action and the login action is not listed with surge protection. 

For reference the surge limits are set here: https://github.com/ros-infrastructure/roswiki/blob/conf/roswiki.py#L110-L122 Note that those are in seconds, with the longest being a 60 second reset. So a 4 hour outage is very surprising. 

If you see this again you can try going directly to: http://wiki.ros.org/action/login/Documentation?action=login

**Comment by NikolausDemmel** [comment]
If I notice this again I will check if login would work while you are already looked out by directly going to http://wiki.ros.org/action/login/Documentation?action=login. At the same time I will recommend to people to stay logged in to prevent it happening in the first place.

If logging in afte the fact doesn't work, or if the issue appears more frequently, I will raise it again and we could look into maybe raising limits for our proxy.

I'll close the issue for now.

Thanks everyone.
