### ISSUE TITLE
Order of robots/books list

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/roswiki#183]
I often notice that a robot or a book gets added to http://wiki.ros.org/Robots / http://wiki.ros.org/Books page, at the top of the list by presumably a person affiliated to a commercial company, author of the book etc. To maintain fairness I suggest to ask the editors to keep certain order. 
Alphabetical? 
Date added? If so asc/descendant?

**Comment by dirk-thomas** [comment]
When these lists grow it becomes more and more difficult to "find" certain entries when they are just appended at the end (or prepended in the front).

For the robots list I think alphabetical order makes the most sense. As far as I can see that is already the case for 99% of the page.

For the books I can see that an alphabetical list would be ok. Certainly editing the list just to move "your" book to the top (as it seems has happened recently) is not nice. Maybe ordering them by their publication date would be the most neutral and clean way? I have done so in http://wiki.ros.org/action/diff/Books?action=diff&rev1=19&rev2=20

Imo the overview page lacks information for a user to select one. You basically have to open most of the subpages to get the necessary information (e.g. what ROS version does it cover?). I added the language and publication date for easier visibility.

PS: the wiki page you created for instructions (http://wiki.ros.org/Robots/AddingRobotEntry) has an unresolved image.

**Comment by tfoote** [comment]
The robots thumbnails are sorted by by the macro to be alphabetical. For the books I think publication date order might be nice. 

Note that I've been working on a replacement for the Robots page. It's available at: http://robots.ros.org/ the source is here: https://github.com/ros-infrastructure/robots.ros.org I've been filling in content before circulating it. Pull-requests welcome for content or suggested layout improvements.

**Comment by 130s** [comment]
Thanks, all clear now. Since you @dirk-thomas took the most cumbersome part, adding the original issue date, I also contributed supported ROS distros and programming languages.

> PS: the wiki page you created for instructions (http://wiki.ros.org/Robots/AddingRobotEntry) has an unresolved image.

Hm, I don't see any problematic image. If you mean [this image](http://wiki.ros.org/Robots/AddingRobotEntry?action=AttachFile&do=get&target=roswiki_pagenotfound.png), that is intentional (when one opens an URL that doesn't yet exist on wiki.ros.org, that's what one sees).

New http://robots.ros.org/ looks fancy!
