### ISSUE TITLE
Use case driven distro recommendations outdated

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/roswiki#190]
http://wiki.ros.org/Distributions#Which_distribution_to_use

@130s Since you added that paragraph initially maybe you can update it.

**Comment by 130s** [comment]
[Done](http://wiki.ros.org/action/info/Distributions?action=diff&rev2=80&rev1=79).
There might be discussions for the change though (e.g. not entirely sure about LTS recommendation).

**Comment by dirk-thomas** [comment]
Thx
