### ISSUE TITLE
Aaron Park from ROBOTIS 

### ISSUE THREAD

**Issue by aaronskpark** [ros-infrastructure/roswiki#191]
Hello, this is Aaron from ROBOTIS.  Could you please give an access (ID: aaronskpark) to edit the page: http://wiki.ros.org/ROBOTIS

Thank you

**Comment by tfoote** [comment]
Please comment on #139

**Comment by dirk-thomas** [comment]
@tfoote I don't know how the current instructions read but based on the number of users which open new tickets (rather then commenting on the existing one) it might be everything but clear.

Maybe it needs to be rephrased? Maybe the referenced tickets needs to be updated to clearly state at the top that it is fine to comment on it even though its closed?

Anyway when users create a ticket I don't think it makes sense to request that they need to refill their request in a different location.

**Comment by tfoote** [comment]
People successfully comment on that ticket most of the time. The large majority of people end up in the right place >500 so far. 

The link is pretty explicit saying to comment ["on this ticket"](https://github.com/ros-infrastructure/roswiki/blob/f9549edc004808183dc42f6639500a19ca4253c9/theme/rostheme.py#L232) 

Feel free to update it to be clearer. I reordered the description at the top of the ticket to give the instructions to comment below in the first line.

> Anyway when users create a ticket I don't think it makes sense to request that they need to refill their request in a different location.

I use that ticket as a record of who has requested if I need to recreate the list I will have one location to review. And if there's any question I can find the username on that page and connect it to the github account.

**Comment by dirk-thomas** [comment]
I agree that the message in the wiki itself is already pretty precise. The new paragraph at the beginning of the ticket is good. I hope it helps to encourage people to comment their (rather then open a new ticket).
