### ISSUE TITLE
rotation two Gears in RViz and Gazebo

### ISSUE THREAD

**Issue by zakizadeh** [ros-infrastructure/roswiki#194]
i have two gears in my urdf . i want rotate two gears in same time . U31_1 and U32_1 are gears .
[image](http://answers.gazebosim.org/upfiles/14837212822134564.jpg)

my urdf :

 <link
    name="link_U31_1">
    <inertial>
      <origin
        xyz="-8.87891218881443E-11 7.94085594724159E-07 -0.00670118881241989"
        rpy="0 0 0" />
      <mass
        value="0.0791354618215319" />
      <inertia
        ixx="0"
        ixy="0"
        ixz="0"
        iyy="0"
        iyz="0"
        izz="0" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file:///home/zakizadeh/catkin_ws3/src/wrist/meshes/link_U31_1.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file:///home/zakizadeh/catkin_ws3/src/wrist/meshes/link_U31_1.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint_U31_1"
    type="revolute">
    <origin
      xyz="0.0375000001895901 0 0.0547500000000001"
      rpy="0 6.93889390390723E-16 0" />
    <parent
      link="link_U33_1" />
    <child
      link="link_U31_1" />
    <axis
      xyz="0 0 1" />
<limit effort="1.0" lower="-1.75" upper="1.75" velocity="3.14"/>
  </joint>
 <link
    name="link_U32_1">
    <inertial>
      <origin
        xyz="-1.49046497366356E-10 -0.000127794819901189 1.88843510273706E-10"
        rpy="0 0 0" />
      <mass
        value="0.019633991990533" />
      <inertia
        ixx="0"
        ixy="0"
        ixz="0"
        iyy="0"
        iyz="0"
        izz="0" />
    </inertial>
    <visual>
      <origin <link
    name="link_U32_1">
    <inertial>
      <origin
        xyz="-1.49046497366356E-10 -0.000127794819901189 1.88843510273706E-10"
        rpy="0 0 0" />
      <mass
        value="0.019633991990533" />
      <inertia
        ixx="0"
        ixy="0"
        ixz="0"
        iyy="0"
        iyz="0"
        izz="0" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file:///home/zakizadeh/catkin_ws3/src/wrist/meshes/link_U32_1.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file:///home/zakizadeh/catkin_ws3/src/wrist/meshes/link_U32_1.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint_U32_1"
    type="revolute">
    <origin
      xyz="-0.0075000004012061 0 0.0422500000000005"
      rpy="1.5707963267949 0 1.5707963267949" />
    <parent
      link="link_U33_1" />
    <child
      link="link_U32_1" />
    <axis
      xyz="0 1 0" />
<limit effort="1.0" lower="-1.75" upper="1.75" velocity="3.14"/>
  </joint>
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file:///home/zakizadeh/catkin_ws3/src/wrist/meshes/link_U32_1.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file:///home/zakizadeh/catkin_ws3/src/wrist/meshes/link_U32_1.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint_U32_1"
    type="revolute">
    <origin
      xyz="-0.0075000004012061 0 0.0422500000000005"
      rpy="1.5707963267949 0 1.5707963267949" />
    <parent
      link="link_U33_1" />
    <child
      link="link_U32_1" />
    <axis
      xyz="0 1 0" />
<limit effort="1.0" lower="-1.75" upper="1.75" velocity="3.14"/>
  </joint>

**Comment by wjwwood** [comment]
This is only for issues with the wiki.ros.org website. Please see http://wiki.ros.org/Support.
