### ISSUE TITLE
Specify dependencies needed for Install + Configure tutorial

### ISSUE THREAD

**Issue by s-moffett** [ros-infrastructure/roswiki#201]
For complete beginners following the Core ROS Tutorials starting at the beginning ([Installing and Configuring Your ROS Environment](http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment)), there's no mention that the Ubuntu apt packages don't include the dependencies needed to complete the tutorial (build-essential for a C++ compiler, etc).

I suggest editing the "1.7 Getting rosinstall" step at the end of the [Ubuntu Installation page](http://wiki.ros.org/kinetic/Installation/Ubuntu) to add the dependencies specified in the [Build from Source page](http://wiki.ros.org/kinetic/Installation/Source) for those who are not building from source and wish to continue with the tutorial or build their own workspaces.

**1.7 Install rosinstall and other dependencies**
[rosinstall](wiki.ros.org/rosinstall) is a frequently used command-line tool in ROS that is distributed separately. It enables you to easily download many source trees for ROS packages with one command.

To install this tool in Ubuntu, run:
`sudo apt-get install python-rosinstall`

If you would like to continue to the [Installing and Configuring Your ROS Environment tutorial](http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment) or create ROS workspaces, install the tools needed to create and manage ROS workspaces:
`sudo apt-get install python-rosdep python-rosinstall-generator python-wstool build-essential`

**Comment by mikaelarguedas** [comment]
Looks good to me, thanks for the suggestion! it'll be less confusing for users.

Given that the next section links to the tutorials page, I think that we can directly add the dependencies in **1.7** without linking to a specific tutorial.
It looks like `python-rosdep` is installed beforehand and used to initialize/update the dependency list in **1.5 Initialize rosdep** so it can be removed from this list.

**Comment by dhood** [comment]
thanks for the suggestion @s-moffett. incorporating the feedback from @mikaelarguedas (the tutorial section was missing for lunar which might be why @s-moffett included it), it's been added to the wiki now to help other users: e.g. 
http://wiki.ros.org/action/info/lunar/Installation/Ubuntu?action=diff&rev2=5&rev1=4
http://wiki.ros.org/lunar/Installation/Ubuntu#Installation.2BAC8-Ubuntu.2BAC8-BinariesBuildDependencies.Dependencies_for_building_packages

**Comment by mikaelarguedas** [comment]
Given that this list of dependencies is already listed on the Install from source page, would it make sense to reuse the list rather than duplicating it?
Or is it because you didn't want rosdep to be in that list given that it's installed earlier in the instructions?

**Comment by dhood** [comment]
I figured that was in line with your initial comment. since it's essentially a prereq for the tutorials IMO it's best to not send users off to another page at that step, but I really don't feel strongly about it -- feel free to change at http://wiki.ros.org/Installation/Ubuntu/BinariesBuildDependencies

**Comment by mikaelarguedas** [comment]
It was inline with my initial comment, I was just wondering if we could include the same BinariesBuildDependencies page in the source install instructions, but I don't really mind either
