### ISSUE TITLE
Changes to "buildfarm/Pull request testing"

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/roswiki#206]
@130s You recently changed the pull request testing wiki page: http://wiki.ros.org/action/diff/buildfarm/Pull%20request%20testing?action=diff&rev1=10&rev2=11

I don't think the current state of the wiki page is better. The page now suggests as the first thing to manually create the webhook. Before the change it first suggested to grant the buildfarm user the necessary access to setup these webhooks automatically. Imo that is the preferred approach and should be mentioned first. Configuring the webhook manually should only be a second / alternative option and therefore be mentioned below.

Can you please update the wiki page accordingly.

**Comment by 130s** [comment]
Oh! Now I get it finally...I'll change.

Btw I wasn't sure where the passage that starts with the following line points to. If you could tell me I can try moving it accordingly.
```
For some org units starting with ros- that is already the case.
```

**Comment by dirk-thomas** [comment]
> For some org units starting with ros- that is already the case.

For some org unit the buildfarm user already has the necessary access privileges.

**Comment by 130s** [comment]
Hope [this change](http://wiki.ros.org/action/info/buildfarm/Pull%20request%20testing?action=diff&rev2=12&rev1=11) looks good enough.
On one of my repos I configured while I was editing the wiki, and I confirmed the PR test is triggered.

**Comment by dirk-thomas** [comment]
Awesome, the updated instructions are much clearer and more detailed than before. Thanks for iterating on it.

I made only minor adjustments in http://wiki.ros.org/action/diff/buildfarm/Pull%20request%20testing?action=diff&rev1=12&rev2=13
