### ISSUE TITLE
Request to add a new external tutorial 

### ISSUE THREAD

**Issue by yahyatawil** [ros-infrastructure/roswiki#215]
An Introduction to Robot Operating System (ROS)
https://www.allaboutcircuits.com/technical-articles/an-introduction-to-robot-operating-system-ros/

**Comment by dhood** [comment]
You can add the tutorial to the "external tutorials" section of this wiki page: http://wiki.ros.org/ROS/Tutorials#External_Tutorials

**Comment by yahyatawil** [comment]
Thanks. But when I try to edit I get the following message: 

>  Note: Hi there, yahyatawil! In an effort to combat spam, we require that users be added to a whitelist to gain edit permissions. To gain edit permissions for yourself, please comment on this GitHub ticket with your wiki UserName, 'yahyatawil', to be added to the whitelist. Thanks for your patience and support.

**Comment by dhood** [comment]
Yep, that's normal; you will have to follow the instructions and comment [here](https://github.com/ros-infrastructure/roswiki/issues/139) to get your username approved for editing (only once)
