### ISSUE TITLE
ERR_BLOCKED_BY_XSS_AUDITOR on chrome when previewing edits

### ISSUE THREAD

**Issue by dhood** [ros-infrastructure/roswiki#219]
On some pages when previewing an edit, Chrome gives this error:

> This page isn’t working
Chrome detected unusual code on this page and blocked it to protect your personal information (for example, passwords, phone numbers, and credit cards).
Try visiting the site's homepage.
ERR_BLOCKED_BY_XSS_AUDITOR

I'm on OS X Chrome 59. The behaviour seems to have been introduced in Chrome 57 ([fixed bug](https://bugs.chromium.org/p/chromium/issues/detail?id=683798)) but continues to be an issue for some pages ([open bug](https://bugs.chromium.org/p/chromium/issues/detail?id=702542)).

The suggested workaround is "configuring your server to send `X-XSS-Protection: 0` along with the response from the POST endpoint"

**Comment by dhood** [comment]
[minimal reproduction](http://wiki.ros.org/testChrome):

```
{{{#!rhtml
 <a href="apt:ros-lunar-desktop-full?refresh=yes" onClick="javascript: _gaq.push(['_trackPageview', '/downloads/map']);">click here</a>
 }}}
```

that it happens with `<a>` + `onClick` + POST matches the description [in this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=702542#c26)

grep says the only pages that have an onClick handler look to be the installation pages, and they don't get edited very often so I wouldn't consider this a priority.

@tfoote are those click stats even useful given that most people probably type the installation command themselves? it'd be the download numbers that are useful, right? if so I'll just remove this handler to prevent users from running into this

**Comment by tfoote** [comment]
Those are not giving useful metrics at the moment. They're all reporting the same page view. We only get ~320 per week. And don't get differentiation. I think it's probably worth just switching to a standard link w/o the onClick event.

**Comment by dhood** [comment]
ok great, thanks for the input @tfoote. I've removed the onClick event from debian and ubuntu install pages for indigo, kinetic and lunar as a workaround, e.g. http://wiki.ros.org/action/info/lunar/Installation/Debian?action=diff&rev2=4&rev1=3
since this error should only affect just a few other pages for EOL distros I'll close this and we can look into a proper fix if we ever need the onClick for something else

**Comment by dirk-thomas** [comment]
Several more pages have that *onclick* handler. You can get a full list by searching through all pages using the script on the wiki server: `./search.py "_gaq.push"`

* cn(2f)hydro(2f)Installation(2f)Ubuntu
* cn(2f)indigo(2f)Installation(2f)Ubuntu
* cn(2f)jade(2f)Installation(2f)Ubuntu
* diamondback(2f)Installation(2f)Ubuntu
* electric(2f)Installation(2f)Ubuntu
* es(2f)hydro(2f)Installation(2f)Ubuntu
* fr(2f)groovy(2f)Installation(2f)Ubuntu
* fuerte(2f)Installation(2f)Ubuntu
* groovy(2f)Installation(2f)Ubuntu
* hydro(2f)Installation(2f)Ubuntu
* ja(2f)groovy(2f)Installation(2f)Ubuntu
* ja(2f)hydro(2f)Installation(2f)Ubuntu
* ja(2f)indigo(2f)Installation(2f)Ubuntu
* ja(2f)kinetic(2f)Installation(2f)Ubuntu
* jade(2f)Installation(2f)Ubuntu
* ko(2f)groovy(2f)Installation(2f)Ubuntu
* lunar(2f)Installation(2f)Gentoo
* testChrome
* th(2f)indigo(2f)Installation(2f)Ubuntu
* tr(2f)indigo(2f)Kurulum(2f)Ubuntu
* tr(2f)jade(2f)Kurulum(2f)Ubuntu
* vn(2f)kinetic(2f)C(c3a0)i(20c491e1bab7)t(2f)Debian
* vn(2f)kinetic(2f)C(c3a0)i(20c491e1bab7)t(2f)Ubuntu

While we might not want to update non-english pages and EOL distros there are still a couple of pages which should be considered to be updated.

**Comment by dhood** [comment]
http://wiki.ros.org/lunar/Installation/Gentoo is the only english non-EOL page that I can see in that list (other than the test page I added); are there others you're referring to @dirk-thomas ? FWI apt usage doesn't apply for gentoo so I will just remove the link in favour of the `emerge` manual command.

**Comment by dirk-thomas** [comment]
`jade(2f)Installation(2f)Ubuntu` is not EOL yet.

**Comment by dhood** [comment]
ok I updated the jade page and removed the link for gentoo. Thank you for pointing out the `search.py` script, I hadn't noticed it before
