### ISSUE TITLE
add robot to wiki

### ISSUE THREAD

**Issue by YKcks** [ros-infrastructure/roswiki#220]
hello,is this?

**Comment by dhood** [comment]
I believe you have found https://github.com/ros-infrastructure/roswiki/issues/139#issuecomment-317634376 to get yourself added to the wiki whitelist. if your question was something else please re-state it

**Comment by mikaelarguedas** [comment]
@YKcks if you want to add a robot on the wiki you need to make a pull request to https://github.com/ros-infrastructure/robots.ros.org following these [contributions guidelines](https://github.com/ros-infrastructure/robots.ros.org/blob/gh-pages/contributing.md)
