### ISSUE TITLE
wiki mirrors only listed on wiki itself?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/roswiki#223]
Is there an 'off site' list of the ROS wiki mirrors somewhere?

The short outage this morning made a user post [ros wiki is down, Do we have any mirror server for that](https://answers.ros.org/question/269962) on ROS Answers, but searching for a list pointed me to the wiki again. Which was unavailable.

One of the mirrors also showed up in the search results, and that had the list, but it would perhaps be nice to have a authoritative list somewhere that is clearly maintained by OSRF.

**Comment by gavanderhoorn** [comment]
It could be btw that such a list / page already exists and I just don't know about it of course.

**Comment by tfoote** [comment]
I'd recommend using the google cache of the Mirrors page. It's recrawled relatively regularly. You can get it by searching and then using the down arrow to get the submenu to request the cached version.

![image](https://user-images.githubusercontent.com/447804/30086107-5790d88e-924e-11e7-9f19-093a69bc7c19.png)

The cached version is text only but gets you all the links to the current mirrors.

**Comment by gavanderhoorn** [comment]
Using the Google cache is an option - and I initially suggested that to the OP of [#q269962](https://answers.ros.org/question/269962).

However, I feel this is not an 'optimal' solution for two reasons:

 1. this relies on Google actually having a cache
 1. this is not known to users

Google not having a cache is admittedly probably not going to occur often, but (anecdotal) I have seen pages that have somehow 'lost' their cache entry and then got it back.

Nr 2 can be addressed by making this 'official' somewhere of course.

---

Thinking about it: would it not be an option to have that list hosted somewhere else? What about `status.ros.org`? Would that allow additional information to appear whenever the wiki is experiencing downtime?

Alternatively a very simple text only page with a header that just lists the mirror sites on some sort of cdn or an amazon bucket (linked from `status.ros.org` and other places) might be enough.

**Comment by PeteBlackerThe3rd** [comment]
I think the status.ros.org website is definitely the right place for a list of mirror sites. Maybe it would be an idea to do a little search engine optimisation so people who google "ROS Wiki down" and other common searches in this situation will find this page.

**Comment by tfoote** [comment]
I added a few links to the status page and included a link to the google cache of the mirrors. That should be enough for most users.

```
If the ROS wiki: https://wiki.ros.org/ is down there are several mirrors including: http://mirror-ap.wiki.ros.org/ in Singapore and http://mirror-eu.wiki.ros.org/ in Ireland. 

The autogenerated documentation from docs.ros.org is also available on mirrors including: http://mirror-ap.docs.ros.org/ in Singapre and http://mirror-eu.docs.ros.org/ in Ireland 

Other mirrors are listed at https://wiki.ros.org/Mirrors if the wiki's offline try Google's Cache: https://webcache.googleusercontent.com/search?q=cache:wiki.ros.org/Mirrors
```
