### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by ethandaniels** [ros-infrastructure/roswiki#230]
User: EthanDaniels

**Comment by mikaelarguedas** [comment]
@ethandaniels added

**Comment by tfoote** [comment]
@ethandaniels please comment on #139 so that we have a record of your request there.

@mikaelarguedas please send people to the other thread so that there's a central record which can be queried and audited connecting github usernames to wiki usernames

**Comment by mikaelarguedas** [comment]
Will do, thanks for the reminder
