### ISSUE TITLE
Badge enhancement to contain further build job information

### ISSUE THREAD

**Issue by nlimpert** [ros-infrastructure/roswiki#232]
Dear all,

as part of our work in ROSIN (see http://rosin-project.eu/) we propose enhancement for the badges generated by the PackageHeader to provide directly visible status information of the latest (and historical) build status.
This is intended to be used next to the "Jenkins Jobs" list in the "Package Links".

The current source for the manifest is generated by docjobs. The intention is to enhance the devel- and testjobs on the buildfarm to generate another YAML-file which can then be parsed by the roswiki scripts similarly to the current manifest.

The buildfarm shall generate the additional information, with the help of a script that is run as a post-build job. This information should contain the following:
 - aggregated_status: an estimation of the current state of the package build - this can either be "stable", "unstable" or any other
 - results_latest_build: a summarization of tests representing "skipped", "failed" and "successfull"
 - history: a limited number of jobs including their job_id, a URI pointing at the website of the buildfarm to the actual job and again a short summarization of tests within the job of interest.

We already implemented a prototype - please find a demonstration in this video:
https://drive.google.com/file/d/0B0d0awOxdi5aa3hFNUxkelEwUmc/view
This video demonstrates the interaction with sample data, which is hardcoded at the moment.

See a screenshot of the badge here:
![ci_enhancement](https://user-images.githubusercontent.com/10144407/31771676-4c2e6ce8-b4dd-11e7-9bb6-d1580d7d7951.png)
The "10/11" part represents 11 total tests of which 10 were successfull, with respect to the field "results_latest_build".

The prototype implementation is available here:
https://github.com/nlimpert/roswiki/tree/nlimpert/ci_enhancements
Please note that this is work in progress as we are upgrading our local instance of a ROS buildfarm (this is why there is no pull request yet).

Please find a sample of devel_jobs.yaml here:
https://github.com/nlimpert/roswiki/blob/nlimpert/ci_enhancements_sample-data/sample_devel_jobs.yaml

With this issue we would like to start a discussion regarding this enhancement and look forward for your comments / suggestions.

Best regards

NIcolas

**Comment by gavanderhoorn** [comment]
@wasowski

**Comment by gavanderhoorn** [comment]
@dirk-thomas / @tfoote: should the discussion about the `ros_buildfarm` extension (and the `yaml` file structure) be moved to `ros-infrastructure/ros_buildfarm`?

**Comment by tfoote** [comment]
This definitely looks interesting. Making sure that we add minimal overhead for the page render is important so we don't overload the wiki. But loading one yaml file should be ok.

For generating the output we should probably talk about it on the ros_buildfarm repo. And have a matching PR here with generating the front end.

@nuclearsandwich FYI

**Comment by gavanderhoorn** [comment]
@tfoote: we decided on using an additional yaml file to avoid increasing load on the buildfarm, similar to how doc jobs generate files only every 3 days. The only difference here is that we generate output after every run of the devel job, as the badge is useless if it shows you stale test results.

**Comment by gavanderhoorn** [comment]
#246 was merged, so closing this one.

**Comment by gavanderhoorn** [comment]
O, I can't close it, as @nlimpert is the OP.

@nlimpert: can you close?

**Comment by nlimpert** [comment]
Done, thanks!
