### ISSUE TITLE
Make wiki mirrors use doc mirrors for API docs (and others)

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/roswiki#234]
Somewhat related to #223.

In many cases when the wiki host is off-line, so is the machine serving `docs.ros.org`. The wiki pages on the various mirrors link to `docs.ros.org` for various things (API docs fi), resulting in dead links whenever this happens.

As the reason to visit the mirrors is typically because the main site is down, would it make sense to somehow change the base URL for the wiki mirrors to point to the doc mirrors as well?

Example: make the 'Code API' link for [angles](http://mirror-eu.wiki.ros.org/angles) point to the [mirrored API docs](http://mirror-eu.docs.ros.org/lunar/api/angles/html), instead of the [regular ones](http://docs.ros.org/lunar/api/angles/html).

**Comment by gavanderhoorn** [comment]
I realise this is hard to automate because not all wiki mirrors also include a doc mirror, but at least the 'official' mirrors (`mirror-ap` and `mirror-eu`) do, so perhaps there is a way to do it for those?

**Comment by tfoote** [comment]
Moved to ros-infrastructure/mirror#12
