### ISSUE TITLE
Older format www.ros.org/wiki/XYZ not redirecting to newer format wiki.ros.org/XYZ

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/roswiki#237]
Partly discussed in [q275773](https://answers.ros.org/question/275773/ros-documentation-link-redirects-to-wrong-url/).

There are many links on e.g. answers.ros.org that use the older format.

**Comment by tfoote** [comment]
This should be resolved now. Please comment back if you see any continuing issues.

**Comment by 130s** [comment]
Confirmed with these links. Thank you!
http://www.ros.org/wiki/tf
http://www.ros.org/wiki/ros_comm
