### ISSUE TITLE
RSS for RecentChanges does not work

### ISSUE THREAD

**Issue by umhan35** [ros-infrastructure/roswiki#275]
After clicking the RSS icon on the RecentChange page (http://wiki.ros.org/RecentChanges), an error returned: `Unknown action rss_rc.`

Screenshot:

![image](https://user-images.githubusercontent.com/3271612/58592756-2bbb0600-8237-11e9-91da-ee270e55e688.png)

**Comment by tfoote** [comment]
We've turned off many of the features of moin moin to prevent overloading the system as we've scaled too high. The rss feed generation is one of them. A PR to remove the icon would be appreciated, but I don't think that we're going to be able to find the resources to enable the rss.
