### ISSUE TITLE
Updates for ROS repository changes 2019-06

### ISSUE THREAD

**Issue by nuclearsandwich** [ros-infrastructure/roswiki#276]
Issue to track documentation which needs updating for the new repository changes.

Since the changes aren't live yet, we shouldn't actually change docs, but let's use this issue to aggregate a list of pages that will need updates.

Collecting a list of places where the change is being updated for future reference
* [x] https://bitbucket.org/osrf/release-tools/pull-requests/841/use-new-packagesrosorg-key-and-shadow/diff
* [x] https://discourse.ros.org/t/new-gpg-keys-deployed-for-packages-ros-org/9454/2
* [x] https://github.com/osrf/docker_templates/pull/65 
* [x] https://wiki.ros.org/Installation/Ubuntu/Sources
* [x] https://github.com/ros-industrial/industrial_ci/pull/373
* [x] https://github.com/ros-infrastructure/rosindex/pull/166

**Comment by nuclearsandwich** [comment]
- [ ] http://wiki.ros.org/ShadowRepository needs to reflect the rename to `ros-testing`.
- [ ] http://wiki.ros.org/SnapshotRepository needs to note the updated repository layout and the presence of unsupported releases.
- [ ] http://wiki.ros.org/melodic/Installation/Ubuntu and all installation instructions for current rosdistros need to use the updated key id.

**Comment by gavanderhoorn** [comment]
Perhaps also rename `wiki/ShadowRepository` to `wiki/TestingRepository` and setup a redirect from the old to the new page?

**Comment by kyrofa** [comment]
> [...] all installation instructions for current rosdistros need to use the updated key id.

Plus Indigo.

**Comment by ruffsl** [comment]
- [x] ROS2 for Docker Library https://github.com/docker-library/official-images/pull/6000
- [x] ROS1 for Docker Library https://github.com/docker-library/official-images/pull/6053
- [x] Update dockerfiles osrf/ros2 nightly and devel https://github.com/osrf/docker_images/pull/266
- [ ] Update legacy dockerfiles with new key and snapshot URL

**Comment by kyrofa** [comment]
* [x] Snapcraft: Trust new key: https://github.com/snapcore/snapcraft/pull/2578
* [ ] Snapcraft: Stop trusting old key: https://github.com/snapcore/snapcraft/pull/2586

**Comment by ipa-mdl** [comment]
https://github.com/ros-industrial/industrial_ci/pull/373 was merged, I will post some migration notes on discourse later

**Comment by rojas70** [comment]
not being able to receive the keys...

> >>$ sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
> Executing: /tmp/tmp.cqVTG3vU0q/gpg.1.sh --keyserver
> hkp://keyserver.ubuntu.com:80
> --recv-key
> C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
> gpg: requesting key AB17C654 from hkp server keyserver.ubuntu.com
> ?: 127.0.0.1: Connection refused
> gpgkeys: HTTP fetch error 7: couldn't connect: Connection refused
> gpg: no valid OpenPGP data found.
> gpg: Total number processed: 0
> gpg: keyserver communications error: keyserver unreachable
> gpg: keyserver communications error: public key not found
> gpg: keyserver receive failed: public key not found

**Comment by nickzherdev** [comment]
This command helped me:
sudo launchpad-getkeys

**Comment by tfoote** [comment]
Finished the last checklist, closing this.
