### ISSUE TITLE
Allowable requests per time to avoid triggering surge protection?

### ISSUE THREAD

**Issue by jwhendy** [ros-infrastructure/roswiki#279]
Greetings,

I'm trying to automate a pretty big update to our [ros-melodic-arch](https://github.com/ros-melodic-arch) effort. One of these involves updating our wiki links. I found the [distribution list](https://github.com/ros/rosdistro/blob/master/melodic/distribution.yaml), but it doesn't have wiki pages at the release package level, so in my script I'm seeing if `https://wiki.ros.org/foo` exists to use that.

```
try:
    wiki = 'https://wiki.ros.org/{}'.format(pkg)
    req = urllib.request.Request(wiki, method='HEAD')
    urllib.request.urlopen(req, timeout=3)
    time.sleep(5)
```
In #182 [the limits](https://github.com/ros-infrastructure/roswiki/blob/conf/roswiki.py#L110-L122) were cited, but it looks like I should be able to do a request every second? Despite `time.sleep(5)` in my script I'm still getting surge protection errors.

Any suggestions on how I can accomplish my aim while not over-burdening the wiki? Upon success, I really only need to do this once.

**Comment by tfoote** [comment]
The wiki is pretty overloaded. We can't really open it up more. There's more relevant discussion at: https://github.com/ros/rosdistro/issues/21660 lets follow up there.

**Comment by jwhendy** [comment]
I think the question is really: "How do [these limits ](https://github.com/ros-infrastructure/roswiki/blob/conf/roswiki.py#L110-L122)apply in practice?

```
surge_action_limits = { # allow max. <count> <action> requests per <dt> secs
    # action: (count, dt)
       'all': (30, 30),
       'show': (30, 60),
       'recall': (50, 60),
       'raw': (20, 40),  # some people use this for css
       'AttachFile': (60, 60),
       'diff': (30, 60),
       'fullsearch': (5, 60),
       'edit': (10, 60),
       'rss_rc': (1, 60),
       'default': (30, 60),
   }
```

What does a page request via the python `requests` library equate to in the above? On the low end, we have 1/min and 6/min, but most others would seem to allow an action every 1-2 seconds. I found I had to use `time.sleep(10)` in order not to get blocked.

I'm not asking to open the wiki, I'm asking how I can respect the current limits from a practical sense :)

**Comment by tfoote** [comment]
Overall you're reading it right. But I think what you can't see is that some pages incur multiple costs if they cause other page loads etc such as via an include mechanism or other things potentially in embedded macros. An empirical approach is likely going to be the most effective. And note that even if you respect these limits they're also set empirically to keep the server running. It's possible that hitting the FullSearch endpoints 5 times per minute might still starve the server as those are very long running. Or if there are others doing the same thing in parallel.

**Comment by jwhendy** [comment]
>But I think what you can't see is that some pages incur multiple costs if they cause other page loads etc such as via an include mechanism or other things potentially in embedded macros.

Thanks for pointing this out. I did not think about subsequent loads.

Should anyone else run into this, I found that creating a page request to `ros.wiki.org/foo` with `time.sleep(10)` built in to my loop was effective.

Thanks for the clarification!
