### ISSUE TITLE
Google+ broken link on the footer.

### ISSUE THREAD

**Issue by seanyen** [ros-infrastructure/roswiki#280]
For every ROS Wiki page, there is a [`Find us on Google+`](https://plus.google.com/113789706402978299308) link and it appears to lead to a 404 page. Perhaps we should remove it?

EDITED: The code for the link is here: https://github.com/ros-infrastructure/roswiki/blob/3da4f94f6b9af4b07ab9858ac86ea64a9a47b80f/theme/rostheme.py#L335

**Comment by tfoote** [comment]
Fixed in #278
