### ISSUE TITLE
gain edit permissions for me .. please

### ISSUE THREAD

**Issue by saheinisch** [ros-infrastructure/roswiki#288]
Could you please gain me edit permissions? 

saheinisch

Thank you very much in advance!

**Comment by mintar** [comment]
You don't need write permissions to this repository. If you want to change something, you should submit a pull request: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests

**Comment by tfoote** [comment]
If you're asking for permission to write to the ROS wiki please comment on #258 as directed.
