### ISSUE TITLE
Docker instruction does not tell tell you to start `roscore`

### ISSUE THREAD

**Issue by jbcpollak** [ros-infrastructure/roswiki#300]
this page: http://wiki.ros.org/action/login/docker/Tutorials/Docker

tells the user to start the ros container with this command:

```
docker run -it ros
```

but this should be:

```
docker run -it ros roscore
```

At least when using melodic.

**Comment by tfoote** [comment]
That's not the intent of that part of the tutorial. The following line is "This will move you into an interactive session with the running container." if you run roscore directly you won't get the interactive shell and won't be able to do anything else.

Please note that this tracker is for the technical side of hosting the wiki, and isn't focused on tracking content changes.

**Comment by jbcpollak** [comment]
If you follow the tutorial by the letter you don't get a functioning instance of the container because roscore isn't running and there is no instructions to start it.

This is confusing for a newbie.

As a new user you aren't able to edit the wiki, where are we supposed to request content changes? The wiki says to request edit access to edit from this repo.
