### ISSUE TITLE
Feature Request: allow pasting images directly into the wiki text editor, same as StackOverflow and GitHub

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [ros-infrastructure/roswiki#305]
Pasting images into a ROS wiki pages seems to be difficult: 

1. exit the editor
1. attach an image
1. re-open the page editor
1. link back to the freshly-attached image with `{{attachment:some_image.png}}`, as is done [with this image here](http://wiki.ros.org/WritingTutorials#How_to_Start)

However, adding images in StackOverflow or GitHub is a breeze: just copy and paste the image right into the text editor and it automatically uploads the image and links to it. Done. 

Please make adding images to the ROS wiki super easy too. 

Update: #306 is a temporary work-around.

**Comment by tfoote** [comment]
This is a feature request for the engine we're using Moin Moin. Please file it upstream. https://moinmo.in/ We won't make a significant change like that to our instance.
