### ISSUE TITLE
KEEP ME OPEN: image store for ROS wiki pages

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [ros-infrastructure/roswiki#306]
Let's use this GitHub issue as a place where a person editing the [ROS wiki](http://wiki.ros.org/) can easily copy and paste an image for reference on their ROS wiki page. This is a temporary (albeit long-term perhaps) work-around for #305. Ex: here's an image:

![image](https://user-images.githubusercontent.com/6842199/84342916-9fd2fe00-ab5b-11ea-8115-c1e6f06e297a.png)

Now, this image can easily be placed on a ROS wiki page like this:

    {{https://user-images.githubusercontent.com/6842199/84342916-9fd2fe00-ab5b-11ea-8115-c1e6f06e297a.png}}

**Comment by ElectricRCAircraftGuy** [comment]
![image](https://user-images.githubusercontent.com/6842199/84356873-a96b5e80-ab79-11ea-99e2-71f447cdfc32.png)

Image required for webviz page: http://wiki.ros.org/Webviz

**Comment by tfoote** [comment]
Hotlinking resources is bad practice unless you're specifically targeting a CDN where you have permission to do so. Having had people use this wiki abused in the past for hotlinking images it's not nice. 

This will also break all the mirrors and other tools designed for working offline. And any future migration effort will be hampered by images hosted elsewhere with ambiguous licenses etc. And if the hotlink breaks we don't have a copy in any backup.
