### ISSUE TITLE
I am getting mails from this list. How to deactivate the same?

### ISSUE THREAD

**Issue by saheinisch** [ros-infrastructure/roswiki#312]
I am getting mails from this list. How to deactivate the same?

Thank you in advance for your support.

**Comment by tfoote** [comment]
It's not clear what mailing list you're referring to. 

We ask that you please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.
