### ISSUE TITLE
"Open Source Robotics Foundation" on every page

### ISSUE THREAD

**Issue by rotu** [ros-infrastructure/roswiki#314]
Every page has ![image](https://user-images.githubusercontent.com/119948/88861216-1dfa6b00-d1c3-11ea-9a18-4c733deb0eab.png)
and a link to http://www.osrfoundation.org/ on the bottom, which redirects to https://www.openrobotics.org/

The url should be updated to avoid the redirect. It's unclear to me whether the logo image should say "Open Source Robotics Foundation" or "Open Robotics".

**Comment by DLu** [comment]
Closed via https://github.com/ros-infrastructure/roswiki/pull/311
