### ISSUE TITLE
Minor package name to reflect the newer version

### ISSUE THREAD

**Issue by palakons** [ros-infrastructure/roswiki#329]
Under "Building your nodes"
http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28c%2B%2B%29 

the sample code below use the older-version "genmsg"
`find_package(catkin REQUIRED COMPONENTS roscpp rospy std_msgs genmsg)`

It should reflect the newer one to match with the previous chapter of the tutorials
`find_package(catkin REQUIRED COMPONENTS roscpp rospy std_msgs message_generation)`

Best regards,
Thanks
Nick

**Comment by tfoote** [comment]
This tracker is for infrastructure related wiki things. For changes in the wiki itself, please make the changes directly. If you're unsure about a change please ask if the change is accurate on answers.ros.org to get confirmation that the change is correct first. 

To make this change on the site you may need to use the [Version Macro](http://wiki.ros.org/WikiMacros#Version) to avoid breaking older systems.
