### ISSUE TITLE
@denesh-globotix @umbertofontana93 Your accounts are very new. To prevent spam, can you please give me a one sentence description of why you need access to the ROS wiki?

### ISSUE THREAD

**Issue by umbertofontana93** [ros-infrastructure/roswiki#332]
@denesh-globotix @umbertofontana93 Your accounts are very new. To prevent spam, can you please give me a one sentence description of why you need access to the ROS wiki?

_Originally posted by @kscottz in https://github.com/ros-infrastructure/roswiki/issues/258#issuecomment-908550071_

I am the new maintainer of some packages released

**Comment by kscottz** [comment]
This is not the correct location for this discussion.
