### ISSUE TITLE
roswiki documentation fails to load latex

### ISSUE THREAD

**Issue by dcmesh** [ros-infrastructure/roswiki#333]
On at least two wiki pages, the example output of an element displays a latex error instead of the intended content. I was unsure of where to report this issue, so I apologize if this is the wrong location.

1) http://wiki.ros.org/urdf/XML/link
2) http://wiki.ros.org/urdf/XML/joint

**Comment by tfoote** [comment]
We can't support the latex plugin anymore, see discussion in  #301. And please consider replacing it with another markup. I see that link 1 has already been replaced.
