### ISSUE TITLE
wiki search bar broken with ros.org changeover

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/roswiki#335]
The search was a specific hosted search page on ros.org which was setup to embed a site specific search google. 

We can just change this to be a generic google search using `site:ros.org`

Reported on [ROS Discourse](https://discourse.ros.org/t/search-in-documentation-broken-returns-a-404/23141/2?u=tfoote)

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/search-in-documentation-broken-returns-a-404/23141/3
